version: "3.8"

services:
  app:
    image: ghcr.io/rlstech/dashfinance:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.uaudash.rule=Host(`dash.railton.eu.org`)"
        - "traefik.http.routers.uaudash.entrypoints=websecure"
        - "traefik.http.routers.uaudash.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.uaudash.loadbalancer.server.port=5000"
    environment:
      - DB_SERVER=192.168.1.8\SQLEXPRESS
      - DB_PORT=62311
      - DB_NAME=uau
      - DB_USER=claude_readonly
      - DB_PASS=ClaudeReadOnly2024!
      - CACHE_FILE=/cache/cache.json
    volumes:
      - dashfinance_cache:/cache
    networks:
      - network_public

volumes:
  dashfinance_cache:

networks:
  network_public:
    external: true
