version: "3.8"

services:
  app:
    image: ghcr.io/rlstech/dashfinance:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.uaudash.rule=Host(`dash.railton.eu.org`)"
        - "traefik.http.routers.uaudash.entrypoints=websecure"
        - "traefik.http.routers.uaudash.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.uaudash.loadbalancer.server.port=5000"
    environment:
      - DB_SERVER=uaudash_cf_proxy
      - DB_PORT=62311
      - DB_NAME=uau
      - DB_USER=claude_readonly
      - DB_PASS=ClaudeReadOnly2024!
      - CACHE_FILE=/cache/cache.json
    volumes:
      - dashfinance_cache:/cache
    networks:
      - network_public
      - network_internal

  cf_proxy:
    image: ghcr.io/rlstech/cf-tcp-proxy:latest
    environment:
      - CF_HOSTNAME=sql.railton.eu.org
      - CF_ACCESS_CLIENT_ID=a5fd8bddd7defb1145bfb0aaf4c35a47.access
      - CF_ACCESS_CLIENT_SECRET=9a03fb7fedce348d66310fedd34ffff10e99242ee9655284f78b09c8d3b9b9b7
      - LISTEN_PORT=62311
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - network_internal

volumes:
  dashfinance_cache:

networks:
  network_public:
    external: true
  network_internal:
    driver: overlay
